version: "3.9"
services:
  test:
    image: "exercise-3"
    volumes:
      - .:/app
    command: python3 -m pytest
  run:
    image: "exercise-3"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - .:/app
    command: python3 main.py